# Generated by Django 4.1.3 on 2022-11-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
