# Generated by Django 4.1.3 on 2022-11-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
